services:
  memos:
    container_name: memos
    image: neosmemo/memos:stable
    restart: unless-stopped
    networks:
      default:
      proxy_external:
        aliases:
          - memos
    volumes:
      - /data/notes:/var/opt/memos
    environment:
      - TZ=Europe/London
    labels:
      traefik.enable: true
      traefik.docker.network: proxy_external
      traefik.http.routers.memos.rule: Host(`${DOMAIN_MEMOS}`)
      traefik.http.routers.memos.entrypoints: tunnel
      traefik.http.routers.memos.service: memos@docker
      traefik.http.services.memos.loadbalancer.server.port: 5230

networks:
  proxy_external:
    external: true