services:
  koillection:
    image: koillection/koillection
    container_name: koillection
    restart: unless-stopped
    ports:
        - 5006:80
    env_file:
        - .env
    depends_on:
        - db
    volumes:
        - /docker/appdata/koillection/uploads:/uploads

  db:
    image: postgres:16
    container_name: db
    restart: unless-stopped
    env_file:
        - .env
    environment:
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
        - "/docker/appdata/koillection/postgresql:/var/lib/postgresql/data"